// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: cmd/v1/cmd.proto

package cmdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*Command_AddCollectible_
	Command isCommand_Command `protobuf_oneof:"command"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_v1_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_v1_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_cmd_v1_cmd_proto_rawDescGZIP(), []int{0}
}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *Command) GetAddCollectible() *Command_AddCollectible {
	if x, ok := x.GetCommand().(*Command_AddCollectible_); ok {
		return x.AddCollectible
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_AddCollectible_ struct {
	AddCollectible *Command_AddCollectible `protobuf:"bytes,1,opt,name=add_collectible,json=addCollectible,proto3,oneof"`
}

func (*Command_AddCollectible_) isCommand_Command() {}

type Command_AddCollectible struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Command_AddCollectible) Reset() {
	*x = Command_AddCollectible{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_v1_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_AddCollectible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_AddCollectible) ProtoMessage() {}

func (x *Command_AddCollectible) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_v1_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_AddCollectible.ProtoReflect.Descriptor instead.
func (*Command_AddCollectible) Descriptor() ([]byte, []int) {
	return file_cmd_v1_cmd_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Command_AddCollectible) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_cmd_v1_cmd_proto protoreflect.FileDescriptor

var file_cmd_v1_cmd_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6d, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x63, 0x6d, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x49, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x5f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x48,
	0x00, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x62, 0x6c,
	0x65, 0x1a, 0x2a, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x09, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42, 0x82, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x76, 0x31, 0x42, 0x08, 0x43, 0x6d, 0x64, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x77, 0x65, 0x62, 0x33, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x76, 0x31,
	0x3b, 0x63, 0x6d, 0x64, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x43,
	0x6d, 0x64, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x06, 0x43, 0x6d, 0x64, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x12, 0x43, 0x6d, 0x64, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x43, 0x6d, 0x64, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_v1_cmd_proto_rawDescOnce sync.Once
	file_cmd_v1_cmd_proto_rawDescData = file_cmd_v1_cmd_proto_rawDesc
)

func file_cmd_v1_cmd_proto_rawDescGZIP() []byte {
	file_cmd_v1_cmd_proto_rawDescOnce.Do(func() {
		file_cmd_v1_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_v1_cmd_proto_rawDescData)
	})
	return file_cmd_v1_cmd_proto_rawDescData
}

var file_cmd_v1_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_v1_cmd_proto_goTypes = []interface{}{
	(*Command)(nil),                // 0: cmd.v1.Command
	(*Command_AddCollectible)(nil), // 1: cmd.v1.Command.AddCollectible
}
var file_cmd_v1_cmd_proto_depIdxs = []int32{
	1, // 0: cmd.v1.Command.add_collectible:type_name -> cmd.v1.Command.AddCollectible
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_v1_cmd_proto_init() }
func file_cmd_v1_cmd_proto_init() {
	if File_cmd_v1_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_v1_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_v1_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_AddCollectible); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cmd_v1_cmd_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Command_AddCollectible_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_v1_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_v1_cmd_proto_goTypes,
		DependencyIndexes: file_cmd_v1_cmd_proto_depIdxs,
		MessageInfos:      file_cmd_v1_cmd_proto_msgTypes,
	}.Build()
	File_cmd_v1_cmd_proto = out.File
	file_cmd_v1_cmd_proto_rawDesc = nil
	file_cmd_v1_cmd_proto_goTypes = nil
	file_cmd_v1_cmd_proto_depIdxs = nil
}
