// @generated by protoc-gen-es v1.1.1
// @generated from file cmd/v1/cmd.proto (package cmd.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message cmd.v1.Command
 */
export const Command = proto3.makeMessageType(
  "cmd.v1.Command",
  () => [
    { no: 1, name: "add_collectible", kind: "message", T: Command_AddCollectible, oneof: "command" },
  ],
);

/**
 * @generated from message cmd.v1.Command.AddCollectible
 */
export const Command_AddCollectible = proto3.makeMessageType(
  "cmd.v1.Command.AddCollectible",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Command_AddCollectible"},
);

