// @generated by protoc-gen-es v1.1.1
// @generated from file token/v1/token.proto (package token.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message token.v1.Token
 */
export const Token = proto3.makeMessageType(
  "token.v1.Token",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "external_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "attributes", kind: "message", T: Token_Attribute, repeated: true },
  ],
);

/**
 * @generated from message token.v1.Token.Attribute
 */
export const Token_Attribute = proto3.makeMessageType(
  "token.v1.Token.Attribute",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Token_Attribute"},
);

